name: Run wakatime-to-toggl everyday
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npx wakatime-to-toggl -w "$WAKATIME_API_KEY" -t "$TOGGL_API_KEY"
              env:
                  TOGGL_API_KEY: '${{ secrets.TOGGL_API_KEY }}'
                  WAKATIME_API_KEY: '${{ secrets.WAKATIME_API_KEY }}'
